# Window settings
width=800
height=340
location=center
show=dmenu
prompt=Select theme
layer=overlay

# Layout
columns=3
image_size=240x144
allow_images=true
insensitive=true
hide_scroll=true
sort_order=default
cache_file=/dev/null
