# Window settings
width=1320
height=840
location=center
show=dmenu
prompt=Select Wallpaper
layer=overlay

# Layout
columns=5
image_size=240x135 # 16:9
allow_images=true
insensitive=true
hide_scroll=true
sort_order=alphabetical
